---
language: node_js
node_js:
  - "4"

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^3"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm run lint
  - npm test
